trigger:
  - develop
  - master
  - release

pool:
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: "Release"

stages:
  - stage: DEV
    condition: eq(variables['Build.SourceBranchName'], 'develop')
    displayName: "Release to Dev"
    jobs:
      - job: Angular
        steps:
          - task: DownloadSecureFile@1
            name: enviromentProdFile
            displayName: 'Download enviroment prod ts file'
            inputs:
              secureFile: 'environment-prod'

          - script: |
              ls -la
              mv $(enviromentProdFile.secureFilePath) src/environments/
              ls -la src/environments/

          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: 'Install Angular Cli With NodeJs'

          - script: |
              npm install -g @angular/cli
              ng config -g cli.warnings.versionMismatch false
              npm install
            displayName: 'npm install dependencies'

          - script: |
              ng build --configuration=production
            displayName: 'Generate Build Dist for Develop Enviroment'



